-- Bản sao đặt cạnh code migration C# (nguồn: doc/ERD/migrations/0003_corebase_v2.sql).
-- Model đổi → sinh lại bằng `dotnet ef migrations script --idempotent` rồi cập nhật CẢ 2 nơi.

-- 2 schema: "core" (Identity + SysMenu/SysMenuRole) và "business" (DTI Weekly) — khớp ranh giới
-- Core/Business ở tầng code, xem doc/kien-truc-core-module.md.
DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'core') THEN
        CREATE SCHEMA core;
    END IF;
END $EF$;
-- __EFMigrationsHistory (schema core): bảng nội bộ EF Core theo dõi migration đã áp dụng
CREATE TABLE IF NOT EXISTS core."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core."__EFMigrationsHistory" WHERE "MigrationId" = '20260816150234_InitialCreate') THEN
        IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'core') THEN
            CREATE SCHEMA core;
        END IF;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core."__EFMigrationsHistory" WHERE "MigrationId" = '20260816150234_InitialCreate') THEN
        IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'business') THEN
            CREATE SCHEMA business;
        END IF;
    END IF;
END $EF$;

-- AspNetRoles: vai trò người dùng (SuperAdmin/Admin/User)
DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core."__EFMigrationsHistory" WHERE "MigrationId" = '20260816150234_InitialCreate') THEN
    CREATE TABLE core."AspNetRoles" (
        "Id" uuid NOT NULL,
        "Name" character varying(256),
        "NormalizedName" character varying(256),
        "ConcurrencyStamp" text,
        CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

-- AspNetUsers: tài khoản đăng nhập (ASP.NET Core Identity, mở rộng thêm FullName/DateCreate/DateUpdate/MustChangePassword)
DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core."__EFMigrationsHistory" WHERE "MigrationId" = '20260816150234_InitialCreate') THEN
    CREATE TABLE core."AspNetUsers" (
        "Id" uuid NOT NULL,
        "FullName" character varying(200) NOT NULL,
        "DateCreate" timestamp with time zone,
        "DateUpdate" timestamp with time zone,
        "MustChangePassword" boolean NOT NULL DEFAULT TRUE,
        "UserName" character varying(256),
        "NormalizedUserName" character varying(256),
        "Email" character varying(256),
        "NormalizedEmail" character varying(256),
        "EmailConfirmed" boolean NOT NULL,
        "PasswordHash" text,
        "SecurityStamp" text,
        "ConcurrencyStamp" text,
        "PhoneNumber" text,
        "PhoneNumberConfirmed" boolean NOT NULL,
        "TwoFactorEnabled" boolean NOT NULL,
        "LockoutEnd" timestamp with time zone,
        "LockoutEnabled" boolean NOT NULL,
        "AccessFailedCount" integer NOT NULL,
        CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

-- CriteriaGroups: nhóm chỉ tiêu đánh giá DTI Weekly
DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core."__EFMigrationsHistory" WHERE "MigrationId" = '20260816150234_InitialCreate') THEN
    CREATE TABLE business."CriteriaGroups" (
        "Id" uuid NOT NULL,
        "Code" character varying(10) NOT NULL,
        "Name" character varying(200) NOT NULL,
        "DisplayOrder" integer NOT NULL,
        "UserCreate" character varying(50),
        "UserUpdate" character varying(50),
        "DateCreate" timestamp with time zone,
        "DateUpdate" timestamp with time zone,
        "IsDelete" boolean NOT NULL,
        CONSTRAINT "PK_CriteriaGroups" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

-- SysMenus: menu điều hướng động (sidebar), tự tham chiếu ParentId cho cây 1 cấp
DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core."__EFMigrationsHistory" WHERE "MigrationId" = '20260816150234_InitialCreate') THEN
    CREATE TABLE core."SysMenus" (
        "Id" uuid NOT NULL,
        "Code" character varying(100) NOT NULL,
        "Name" character varying(200) NOT NULL,
        "Route" character varying(200),
        "Icon" character varying(50),
        "ParentId" uuid,
        "DisplayOrder" integer NOT NULL,
        "UserCreate" character varying(50),
        "UserUpdate" character varying(50),
        "DateCreate" timestamp with time zone,
        "DateUpdate" timestamp with time zone,
        "IsDelete" boolean NOT NULL,
        CONSTRAINT "PK_SysMenus" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_SysMenus_SysMenus_ParentId" FOREIGN KEY ("ParentId") REFERENCES core."SysMenus" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

-- AspNetRoleClaims: claim cấp role (Identity sinh sẵn, chưa dùng)
DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core."__EFMigrationsHistory" WHERE "MigrationId" = '20260816150234_InitialCreate') THEN
    CREATE TABLE core."AspNetRoleClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "RoleId" uuid NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES core."AspNetRoles" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

-- AspNetUserClaims: claim cấp user (Identity sinh sẵn, chưa dùng)
DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core."__EFMigrationsHistory" WHERE "MigrationId" = '20260816150234_InitialCreate') THEN
    CREATE TABLE core."AspNetUserClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" uuid NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES core."AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

-- AspNetUserLogins: đăng nhập ngoài (Google/Microsoft...), chưa dùng
DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core."__EFMigrationsHistory" WHERE "MigrationId" = '20260816150234_InitialCreate') THEN
    CREATE TABLE core."AspNetUserLogins" (
        "LoginProvider" text NOT NULL,
        "ProviderKey" text NOT NULL,
        "ProviderDisplayName" text,
        "UserId" uuid NOT NULL,
        CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
        CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES core."AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

-- AspNetUserRoles: gán role cho user (nhiều-nhiều)
DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core."__EFMigrationsHistory" WHERE "MigrationId" = '20260816150234_InitialCreate') THEN
    CREATE TABLE core."AspNetUserRoles" (
        "UserId" uuid NOT NULL,
        "RoleId" uuid NOT NULL,
        CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
        CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES core."AspNetRoles" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES core."AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

-- AspNetUserTokens: token nội bộ Identity (reset password, 2FA)
DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core."__EFMigrationsHistory" WHERE "MigrationId" = '20260816150234_InitialCreate') THEN
    CREATE TABLE core."AspNetUserTokens" (
        "UserId" uuid NOT NULL,
        "LoginProvider" text NOT NULL,
        "Name" text NOT NULL,
        "Value" text,
        CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
        CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES core."AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

-- Criteria: chỉ tiêu đánh giá cụ thể, thuộc 1 CriteriaGroups
DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core."__EFMigrationsHistory" WHERE "MigrationId" = '20260816150234_InitialCreate') THEN
    CREATE TABLE business."Criteria" (
        "Id" uuid NOT NULL,
        "Code" character varying(20) NOT NULL,
        "Name" text NOT NULL,
        "GroupId" uuid NOT NULL,
        "MaxScore" numeric(6,2) NOT NULL,
        "UserCreate" character varying(50),
        "UserUpdate" character varying(50),
        "DateCreate" timestamp with time zone,
        "DateUpdate" timestamp with time zone,
        "IsDelete" boolean NOT NULL,
        CONSTRAINT "PK_Criteria" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Criteria_CriteriaGroups_GroupId" FOREIGN KEY ("GroupId") REFERENCES business."CriteriaGroups" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

-- SysMenuRoles: role nào được thấy menu nào (nhiều-nhiều)
DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core."__EFMigrationsHistory" WHERE "MigrationId" = '20260816150234_InitialCreate') THEN
    CREATE TABLE core."SysMenuRoles" (
        "SysMenuId" uuid NOT NULL,
        "RoleId" uuid NOT NULL,
        CONSTRAINT "PK_SysMenuRoles" PRIMARY KEY ("SysMenuId", "RoleId"),
        CONSTRAINT "FK_SysMenuRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES core."AspNetRoles" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_SysMenuRoles_SysMenus_SysMenuId" FOREIGN KEY ("SysMenuId") REFERENCES core."SysMenus" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

-- CriteriaAssessments: kết quả đánh giá 1 Criteria theo từng kỳ (ngày của DateCreate = kỳ)
DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core."__EFMigrationsHistory" WHERE "MigrationId" = '20260816150234_InitialCreate') THEN
    CREATE TABLE business."CriteriaAssessments" (
        "Id" uuid NOT NULL,
        "CriteriaId" uuid NOT NULL,
        "ProgressPercent" numeric(5,2) NOT NULL,
        "SelfScore" numeric(6,2),
        "VerifiedScore" numeric(6,2),
        "Status" character varying(50),
        "OwnerId" uuid,
        "Deadline" date,
        "Note" text,
        "UserCreate" character varying(50),
        "UserUpdate" character varying(50),
        "DateCreate" timestamp with time zone,
        "DateUpdate" timestamp with time zone,
        "IsDelete" boolean NOT NULL,
        CONSTRAINT "PK_CriteriaAssessments" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_CriteriaAssessments_AspNetUsers_OwnerId" FOREIGN KEY ("OwnerId") REFERENCES core."AspNetUsers" ("Id") ON DELETE SET NULL,
        CONSTRAINT "FK_CriteriaAssessments_Criteria_CriteriaId" FOREIGN KEY ("CriteriaId") REFERENCES business."Criteria" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

-- CriteriaEvidences: minh chứng đính kèm 1 CriteriaAssessments (nhiều dòng/bản ghi)
DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core."__EFMigrationsHistory" WHERE "MigrationId" = '20260816150234_InitialCreate') THEN
    CREATE TABLE business."CriteriaEvidences" (
        "Id" uuid NOT NULL,
        "CriteriaAssessmentId" uuid NOT NULL,
        "Content" text NOT NULL,
        "OrderIndex" integer NOT NULL,
        "UserCreate" character varying(50),
        "UserUpdate" character varying(50),
        "DateCreate" timestamp with time zone,
        "DateUpdate" timestamp with time zone,
        "IsDelete" boolean NOT NULL,
        CONSTRAINT "PK_CriteriaEvidences" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_CriteriaEvidences_CriteriaAssessments_CriteriaAssessmentId" FOREIGN KEY ("CriteriaAssessmentId") REFERENCES business."CriteriaAssessments" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core."__EFMigrationsHistory" WHERE "MigrationId" = '20260816150234_InitialCreate') THEN
    CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON core."AspNetRoleClaims" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core."__EFMigrationsHistory" WHERE "MigrationId" = '20260816150234_InitialCreate') THEN
    CREATE UNIQUE INDEX "RoleNameIndex" ON core."AspNetRoles" ("NormalizedName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core."__EFMigrationsHistory" WHERE "MigrationId" = '20260816150234_InitialCreate') THEN
    CREATE INDEX "IX_AspNetUserClaims_UserId" ON core."AspNetUserClaims" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core."__EFMigrationsHistory" WHERE "MigrationId" = '20260816150234_InitialCreate') THEN
    CREATE INDEX "IX_AspNetUserLogins_UserId" ON core."AspNetUserLogins" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core."__EFMigrationsHistory" WHERE "MigrationId" = '20260816150234_InitialCreate') THEN
    CREATE INDEX "IX_AspNetUserRoles_RoleId" ON core."AspNetUserRoles" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core."__EFMigrationsHistory" WHERE "MigrationId" = '20260816150234_InitialCreate') THEN
    CREATE INDEX "EmailIndex" ON core."AspNetUsers" ("NormalizedEmail");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core."__EFMigrationsHistory" WHERE "MigrationId" = '20260816150234_InitialCreate') THEN
    CREATE UNIQUE INDEX "UserNameIndex" ON core."AspNetUsers" ("NormalizedUserName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core."__EFMigrationsHistory" WHERE "MigrationId" = '20260816150234_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Criteria_Code_Active" ON business."Criteria" ("Code") WHERE "IsDelete" = false;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core."__EFMigrationsHistory" WHERE "MigrationId" = '20260816150234_InitialCreate') THEN
    CREATE INDEX "IX_Criteria_GroupId" ON business."Criteria" ("GroupId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core."__EFMigrationsHistory" WHERE "MigrationId" = '20260816150234_InitialCreate') THEN
    CREATE INDEX "IX_CriteriaAssessments_CriteriaId_DateCreate" ON business."CriteriaAssessments" ("CriteriaId", "DateCreate");
    END IF;
END $EF$;

-- Vá tay: 1 ngày chỉ có tối đa 1 CriteriaAssessments chưa xoá mềm / Criteria (EF không diễn đạt
-- được CAST trong HasIndex). Dùng hàm IMMUTABLE (ép UTC trước khi cắt ngày) — CAST trực tiếp bị
-- Postgres từ chối vì phụ thuộc TimeZone session (lỗi 42P17).
CREATE OR REPLACE FUNCTION business.criteria_assessment_date_utc(ts timestamptz)
RETURNS date
LANGUAGE sql
IMMUTABLE
AS $$
    SELECT (ts AT TIME ZONE 'UTC')::date;
$$;

CREATE UNIQUE INDEX IF NOT EXISTS "UX_CriteriaAssessments_CriteriaId_DateCreate_Day"
    ON business."CriteriaAssessments" ("CriteriaId", business.criteria_assessment_date_utc("DateCreate"))
    WHERE "IsDelete" = false;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core."__EFMigrationsHistory" WHERE "MigrationId" = '20260816150234_InitialCreate') THEN
    CREATE INDEX "IX_CriteriaAssessments_OwnerId" ON business."CriteriaAssessments" ("OwnerId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core."__EFMigrationsHistory" WHERE "MigrationId" = '20260816150234_InitialCreate') THEN
    CREATE INDEX "IX_CriteriaEvidences_CriteriaAssessmentId" ON business."CriteriaEvidences" ("CriteriaAssessmentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core."__EFMigrationsHistory" WHERE "MigrationId" = '20260816150234_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_CriteriaGroups_Code_Active" ON business."CriteriaGroups" ("Code") WHERE "IsDelete" = false;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core."__EFMigrationsHistory" WHERE "MigrationId" = '20260816150234_InitialCreate') THEN
    CREATE INDEX "IX_SysMenuRoles_RoleId" ON core."SysMenuRoles" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core."__EFMigrationsHistory" WHERE "MigrationId" = '20260816150234_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_SysMenus_Code" ON core."SysMenus" ("Code");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core."__EFMigrationsHistory" WHERE "MigrationId" = '20260816150234_InitialCreate') THEN
    CREATE INDEX "IX_SysMenus_ParentId" ON core."SysMenus" ("ParentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core."__EFMigrationsHistory" WHERE "MigrationId" = '20260816150234_InitialCreate') THEN
    INSERT INTO core."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260816150234_InitialCreate', '10.0.11');
    END IF;
END $EF$;
COMMIT;

